### ISSUE TITLE
Requests Times Out

### ISSUE THREAD

**Issue by odiaseo** [2Parale/2Performant-php#17]
API requests times out after 5sec. Add option to specify time when making requests. See error message below
```cURL error 28: Operation timed out after 5005 milliseconds with 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)```

**Comment by tetele** [comment]
Although not documented, this is already possible. All you need to do is

    Api::init('https://api.2performant.com', [ 'http' => [ 'timeout'  => 2.0 ] ]);

before making any request to change the default timeout to 2 seconds.

I'll add it in the docs.

**Comment by tetele** [comment]
Updated https://github.com/2Parale/2Performant-php/wiki/Usage-examples
