### ISSUE TITLE
Nu se poate instala, nu exista pachetul pentru nici un level de stability

### ISSUE THREAD

**Issue by WindowsAndLinux** [2Parale/2Performant-php#21]
Salut.
Incerc sa instalez pachetul conform "instructiunilor".
Asta-i mesajul pe care il primesc:
[InvalidArgumentException]                                                                                                               
  Could not find package 2Performant/2Performant-php at any version for your minimum-stability (stable). Check the package spelling or yo  
  ur minimum-stability  
Ma poti ajuta sa-l instalez ?

**Comment by udan** [comment]
Poti sa posteri continutul fisierului composer.json?

**Comment by WindowsAndLinux** [comment]
care din ele ? ala de l-am primit in pachetul 2p, care l-am descarcat tot de aici de pe github, sau cel care s-a generat cand am rulat comenzile de instalare ?

**Comment by udan** [comment]
Cel Din radacina proiectului tau

**Comment by WindowsAndLinux** [comment]
{
    "name": "2performant/2performant-php",
    "description": "PHP wrapper for 2Performant API",
    "type": "library",
    "keywords": ["2Performant", "API", "PHP", "HTTP", "REST"],
    "homepage": "http://github.com/2Parale/2Performant-PHP",
    "license": "MIT",
    "authors": [
        {
            "name": "Tudor Sandu",
            "email": "tm.sandu@gmail.com",
            "homepage": "http://tudorsandu.ro",
            "role": "Developer"
        }
    ],
    "support": {
        "email": "support@2performant.com",
        "docs": "http://doc.2performant.com/"
    },
    "require": {
        "guzzlehttp/guzzle": "~6.2"
    },
    "autoload": {
        "psr-4": {
            "TPerformant\\API\\": "src/"
        }
    }
}

**Comment by udan** [comment]
Acesta este fișierul din librăria pe care vrei sa o adaugi ca și dependință in proiectul tău. M-a interesează cel din proiectul tău.

**Comment by WindowsAndLinux** [comment]
Eu nu am nici un proiect anume. Conform instructiunilor de instalare de pe pagina Api 2p, am procedat cu cei 2 pasi, la al doilea pas deja mi se afiseaza eroarea.
It's recommended to install the library using Composer.

    curl -sS https://getcomposer.org/installer | php
Then, install the library (along with its dependencies)

    php composer.phar require 2Performant/2Performant-php
Atat am facut la require.. deja apare eroarea.
Nu am ajuns la faza de a crea un proiect, in care sa utilizez librariile, de vreme ce ele nu se instaleaza

**Comment by tetele** [comment]
Oricum ti se va genera un fisier `composer.json`, asa cum zice si @udan.

Exista 2 abordari:

    php composer.phar require 2Performant/2Performant-php:dev-1.0-wip

sau sa setezi `minimum-stability` in fisierul `composer.json` generat (vezi aici cum https://getcomposer.org/doc/04-schema.md#minimum-stability).

**Comment by WindowsAndLinux** [comment]
Root package '2performant/2performant-php' cannot require itself in its composer.json
Did you accidentally name your root package after an external package?

**Comment by tetele** [comment]
Nu inteleg cum ai reusit sa primesti eroarea asta. Incearca asa:

1. Creeaza un folder nou in care creezi un fisier denumit `composer.json` cu urmatorul continut:

        {
            "require": {
                "2performant/2performant-php": "1.*"
            },
            "minimum-stability": "dev"
        }

2. Deschide un terminal catre folder-ul nou creat si ruleaza `composer install`

Ar trebui sa iti mearga acum. Si studiaza un pic [cum functioneaza composer](https://getcomposer.org/doc/).

**Comment by WindowsAndLinux** [comment]
Re: cum am primit eroarea asta, doar ti-am scris mai sus.
Am urmat pasii propusi de 2p, si de voi, aici in thread.

**Comment by WindowsAndLinux** [comment]
re: sa studiez un pic
ok, cand voi avea vreme, arunc o privire si pe acolo
mersi pt. ajutor

**Comment by tetele** [comment]
N-ai pentru ce.

N-ai specificat clar ce ai facut. Presupun ca ai editat `composer.json` care e deja in pachet (in loc sa creezi unul nou), ceea ce nu are sens, motiv pentru care ti-am recomandat sa mai arunci un ochi pe composer si cum functioneaza.

**Comment by WindowsAndLinux** [comment]
Omule bun, am specificat super foarte clar ce am facut :)
Doar am urmat pasii gasiti in "instructiunile" 2p api
Da' stai asa, de ce nu pui si acolo, direct doar ce mi-ai zis mie aici:
fa un fisier cu continutul asta (ce mi-ai zis mai sus), si da-i comanda install
Ca asa... in 30 de secunde a fost instalat totul :)
