### ISSUE TITLE
Composer install fails due to no stable version

### ISSUE THREAD

**Issue by rollandb** [2Parale/2Performant-php#22]
When running the composer install as per readme, install fails with the following error:

[InvalidArgumentException]
Could not find package 2Performant/2Performant-php at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

**Comment by tetele** [comment]
Check out [this page](https://github.com/2Parale/2Performant-php/wiki/Installation-instructions). It says there that

> If you get a "stability level" error upon installation, please read about how to use the minimum-stability property in Composer https://getcomposer.org/doc/04-schema.md#minimum-stability
