### ISSUE TITLE
Get products feed issue

### ISSUE THREAD

**Issue by lzomedia** [2Parale/2Performant-php#24]
Hy I'm using 'getAffiliateProducts' to get the affiliate products from a feed but the thing is I only get 20 results.
Is there any way to increase the number of results that I get? 
I had a look to the core but I don't find anything related to pagination.
Can you direct me in the right way?

**Comment by tetele** [comment]
Try something like
```
$filter = new AffiliateProductFilter();
for($page = 1; $page <= $numPages; $page++) {
  $products = $api->getAffiliateProducts($auth, $productFeed, $filter->page($page));
}
```
